@startuml
' https://plantuml.com/de/skinparam
' https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html

skinparam DefaultFontName Hack
'skinparam Handwritten True
'skinparam monochrome True
skinparam shadowing false
allow_mixing
'skinparam linetype ortho

skinparam RoundCorner 10
skinparam ComponentBorderColor Black

skinparam {

    Actor {
        BorderColor Black
        BackgroundColor White
        'BackgroundColor hidden 'Damit etwas verschwindet"
    }

    Component {
        BorderColor Black
        BackgroundColor AliceBlue
        ArrowThickness 2
    }

    Database {
        BorderColor Black
        BackgroundColor AliceBlue
    }

    usecase {
        BorderColor Black
        BackgroundColor AliceBlue
    }

    rectangle {
        BorderColor Black
        BackgroundColor AliceBlue
    }

    node {
        BorderColor Black
        BackgroundColor White
    }

    requirement {
        BorderColor Black
        BackgroundColor White
    }

    card {
        BorderColor Black
        BackgroundColor White
    }

    object {
        BorderColor Black
        BackgroundColor AliceBlue
    }

    class {
        BorderColor Black
        BackgroundColor AliceBlue
    }
   file {
        BorderColor Black
        BackgroundColor AliceBlue
        }
}

@enduml