@startmindmap
* TOC
**[#Orange] 1.Basic Theory
***[#lightblue] 1.1.Foundation
****[#lightgreen] 1.1.1.Rule 1
****[#lightgreen] 1.1.2.Rule 2
***[#lightblue] 1.2.Advanced
**[#Orange] 2.Complex Theory
***[#lightblue] 2.1.Some Math
****[#lightgreen] 2.1.1.Equation 1
****[#lightgreen] 2.1.2.Equation 2
***[#lightblue] 2.2.Some Programming
left side
**[#Orange] 3.Golang Basics
***[#lightblue] 3.1.Data Structures
****[#lightgreen] 3.1.1.Array
****[#lightgreen] 3.1.2.Dictionary
@endmindmap
