@startmindmap
* TOC
**[#Orange]   Introduction 
***[#lightblue]  1 Theory 
****[#lightgreen]  1.1 Basic Theory 
*****[#lightyellow]  1.1.1 Foundation 
******[#lightcyan]  1.1.1.1 Rule 1 
*******[#Ivory]  1.1.1.1.1 Left side of rule 
********[#MintCream]  1.1.1.1.1.1 Parameter of rule  
******[#lightcyan]  1.1.1.2 Rule 2 
*****[#lightyellow]  1.1.2 Advanced 
****[#lightgreen]  1.2 Complex Theory 
*****[#lightyellow]  1.2.1 Some Math 
******[#lightcyan]  1.2.1.1 Equation 1 
******[#lightcyan]  1.2.1.2 Equation 2 
*****[#lightyellow]  1.2.2 Some Programming 
***[#lightblue]  2 Use Cases 
****[#lightgreen]  2.1 Use Case A 
*****[#lightyellow]  2.1.1 Pre Conditions 
******[#lightcyan]  2.1.1.1 Pre-Condition A 
******[#lightcyan]  2.1.1.2 Pre-Condition B 
*****[#lightyellow]  2.1.2 Pre Condition 
****[#lightgreen]  2.2 Use Case B 
*****[#lightyellow]  2.2.1 Pre Conditions 
******[#lightcyan]  2.2.1.1 Pre-Condition A 
******[#lightcyan]  2.2.1.2 Pre-Condition B 
*****[#lightyellow]  2.2.2 Pre Condition 
left side
**[#Orange]   Implementation 
***[#lightblue]  3 Implementation in Golang 
****[#lightgreen]  3.1 Golang Basics 
*****[#lightyellow]  3.1.1 Data Structures 
******[#lightcyan]  3.1.1.1 Array 
******[#lightcyan]  3.1.1.2 Dictionary 
*****[#lightyellow]  3.1.2 Concurrency 
@endmindmap
